In [66]:
import numpy as np

In [67]:
Y = np.array([
    [5, 3, 0, 1],
    [0, 4, 5, 0],
    [3, 0, 2, 5]
])
print(Y)

[[5 3 0 1]
 [0 4 5 0]
 [3 0 2 5]]


In [68]:
num_users, num_items = Y.shape
num_features = 2

X = np.random.randn(num_users, num_features) *1.000
W = np.random.randn(num_items, num_features) *1.000
print(W)

[[-1.40208148 -1.27087565]
 [-0.81687507  2.20908977]
 [ 0.18351842  1.76027361]
 [ 0.44364554 -0.42072114]]


In [69]:
prediction=np.dot(X,W.T)
squared_error= (prediction - Y) ** 2

In [70]:
mask=(Y >0)
final_error=squared_error[mask]
print(final_error)

[1.11971587e+01 4.09349397e+01 9.39488589e-02 1.02607027e+02
 9.83081185e+01 1.79732361e+01 4.71266835e-01 3.49390287e+01]


In [71]:
cost=np.mean(final_error)
print(cost)

38.31559050627621


In [72]:
epochs=1000
learning_rate = 0.01
reg_lambda = 0.0001
num_ratings = np.sum(mask)

for epoch in range (epochs):
    prediction=np.dot(X,W.T)
    error=(prediction-Y)*mask
    grad_x = (np.dot(error, W) + reg_lambda * X) / num_ratings
    grad_w = (np.dot(error.T, X) + reg_lambda * W) / num_ratings
    X = X - learning_rate * grad_x
    W = W - learning_rate * grad_w
    cost = np.sum(error**2) / np.sum(mask)

    if epoch % 100 == 0:
        print(f"Epoch {epoch} | Cost: {cost:.4f}")

Epoch 0 | Cost: 38.3156
Epoch 100 | Cost: 10.2465
Epoch 200 | Cost: 3.1835
Epoch 300 | Cost: 0.5693
Epoch 400 | Cost: 0.1066
Epoch 500 | Cost: 0.0251
Epoch 600 | Cost: 0.0080
Epoch 700 | Cost: 0.0036
Epoch 800 | Cost: 0.0022
Epoch 900 | Cost: 0.0015


In [74]:
print("Original Ratings (Y)")
print(Y)

print("\nFinal Predictions")
final_preds = np.clip(np.dot(X, W.T), 1, 5)
print(np.round(final_preds, 2))

Original Ratings (Y)
[[5 3 0 1]
 [0 4 5 0]
 [3 0 2 5]]

Final Predictions
[[5.   2.93 3.89 1.01]
 [5.   4.05 4.98 2.28]
 [2.99 2.87 2.02 5.  ]]
